version: '3.8'

services:
  bot_gateway:
    build: ./bot_gateway
    depends_on:
      - user_service
      - minio
      - matchmaking_service
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      TELEGRAM_TOKEN: "6708064233:AAE6yHF5pHxCtWNLLWPGJMU7Zrtrfgz6UvA"
      MINIO_PUBLIC_URL: "http://192.168.1.100:9000"
      MATCH_SERVICE_URL: "http://matchmaking_service:8000/match"
    ports:
      - "8080:80"
    networks:
      - dating_net

  user_service:
    build: ./user_service
    ports:
      - "8000:8000"
    networks:
      - dating_net

  rating_service:
    build: ./rating_service
    ports:
      - "8001:8000"
    networks:
      - dating_net

  matchmaking_service:
    build: ./matchmaking_service
    depends_on:
      - redis
    networks:
      - dating_net
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    networks:
      - dating_net

  minio:
    image: minio/minio
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    volumes:
      - minio_data:/data
    networks:
      - dating_net

volumes:
  minio_data:

networks:
  dating_net:
